#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
#Copyright (c) 2016 YLWS-4617
#This shell program is used to help users us ssr-bash in the easiest way.
#Please obey the original license in this project file! thank you.
######Check Root######
[ $(id -u) != "0" ] && { echo "${CFAILURE}Error: You must be root to run this script${CEND}"; exit 1; }
######Check Root######

function echocopyright(){
	echo '欢迎来到SSR-Bash管理程序！Author: 雨落无声'
	echo '默认加密方式：chacha20'
	echo '可选择协议：auth_sha1_compatible'
	echo '可选择混淆：http_simple_compatible'
	echo ''
	echo "请输入序号来选择功能：\n"
}

function showchoice(){
	echo '1.服务管理'
	echo '2.用户管理'
	echo '3.流量控制'
	echo ''
}

function serverchoice(){
	echo '1.启动服务'
	echo '2.停止服务'
	echo '3.重启服务'
	echo '4.服务状态'
	echo ''
}


function userchoice(){
	echo '1.添加用户'
	echo '2.删除用户'
	echo '3.修改用户密码'
	echo '4.显示用户密码信息'
	echo '5.显示所有用户密码信息'
}

function bandchoice(){
	echo '1.显示用户流量信息'
	echo '2.显示所有用户流量信息'
	echo '3.修改用户流量限制'
	echo '4.修改所有用户流量限制'
	echo '5.清零用户流量使用量'
	echo '6.清零所有用户流量使用量'
	echo '7.显示已添加的iptables规则'
	echo ''
}


#Main
clear
echocopyright
showchoice

while :; do echo

	read -p "请选择： " choice

	if [[ ! $choice =~ ^[1-3]$ ]]; then
		echo "${CWARNING}输入错误! 请输入正确的数字!${CEND}"
	else
		break	
	fi
done

if [[ $choice == 1 ]];then

	serverchoice

	while :; do echo
		read -p "请选择： " schoice
		if [[ ! $schoice =~ ^[1-4]$ ]]; then
			echo "${CWARNING}输入错误! 请输入正确的数字!${CEND}"
		else
			break	
		fi
	done

	if [[ $schoice == 1 ]];then
		bash /usr/local/SSR-Bash/ssadmin.sh start
	fi

	if [[ $schoice == 2 ]];then
		bash /usr/local/SSR-Bash/ssadmin.sh stop
	fi

	if [[ $schoice == 3 ]];then
		bash /usr/local/SSR-Bash/ssadmin.sh restart
	fi

	if [[ $schoice == 4 ]];then
		bash /usr/local/SSR-Bash/ssadmin.sh status
	fi
fi



if [[ $choice == 2 ]];then
	userchoice
	while :; do echo
		read -p "请选择： " uchoice
		if [[ ! $uchoice =~ ^[1-5]$ ]]; then
			echo "${CWARNING}输入错误! 请输入正确的数字!${CEND}"
		else
			break
		fi
	done

	if [[ $uchoice == 1 ]];then
		read -p "请输入新用户端口： " newport
		read -p "请输入新用户端口的密码： " newpassword
		read -p "请输入新用户流量限制（例如 10G）： " newlimit
		bash /usr/local/SSR-Bash/ssadmin.sh add $newport $newpassword $newlimit
	fi

	if [[ $uchoice == 2 ]];then
		read -p "请输入要删除的用户端口： " delport
		bash /usr/local/SSR-Bash/ssadmin.sh del $delport
		echo "端口为 $delport 的用户删除成功！"
	fi

	if [[ $uchoice == 3 ]];then
		read -p "请输入要修改密码的用户的端口： " cport
		read -p "请输入新密码： " cpassword
		bash /usr/local/SSR-Bash/ssadmin.sh cpw $cport $cpassword
		echo "端口为 $cport 的用户密码已成功更改为 $cpassword"
	fi

	if [[ $uchoice == 4 ]];then
		read -p "请输入要查看密码的用户端口： " showport
		bash /usr/local/SSR-Bash/ssadmin.sh showpw $showport
	fi

	if [[ $uchoice == 5 ]];then
		bash /usr/local/SSR-Bash/ssadmin.sh showpw
	fi
fi


if [[ $choice == 3 ]];then

	bandchoice

	while :; do echo
		read -p "请选择： " bchoice
		if [[ ! $bchoice =~ ^[1-7]$ ]]; then
			echo "${CWARNING}输入错误! 请输入正确的数字!${CEND}"
		else
			break
		fi
	done

	if [[ $bchoice == 1 ]];then
		read -p "请输入要查看流量的用户端口： " bport
		bash /usr/local/SSR-Bash/ssadmin.sh show $bport
	fi

	if [[ $bchoice == 2 ]];then
		bash /usr/local/SSR-Bash/ssadmin.sh show
	fi
	
	if [[ $bchoice == 3 ]];then
		read -p "请输入要修改流量限制的用户端口： " climitport
		read -p "请输入新的流量限制： " climit
		bash /usr/local/SSR-Bash/ssadmin.sh clim $climitport $climit
		echo "端口为 $climitport 的用户的流量限制已改为 $climit"
	fi
	
	if [[ $bchoice == 4 ]];then
		read -p "请输入对所有用户的新的流量限制： " climitforallusers
		bash /usr/local/SSR-Bash/ssadmin.sh change_all_limit $climitforallusers
		echo "所有用户的流量限制已改为 $climitforallusers"
	fi
	
	if [[ $bchoice == 5 ]];then
		read -p "请输入要清零已用流量的用户端口： " zeroport
		bash /usr/local/SSR-Bash/ssadmin.sh rused $zeroport
		echo "端口号为 $zeroport 的用户已用流量已清零"
	fi
	
	if [[ $bchoice == 6 ]];then
		bash /usr/local/SSR-Bash/ssadmin.sh reset_all_used
		echo '所有用户已用流量已清零！'
	fi
	
	if [[ $bchoice == 7 ]];then
		bash /usr/local/SSR-Bash/ssadmin.sh lrules
	fi	
fi